name: TEST Govern-Console CI/CD
on:
  push:
    branches:
      - 'DAO-368-test-govern-ci'

env:
  working-directory: packages/govern-console

jobs:
  build-deploy-develop:
    strategy:
      matrix:
        environment: ['Rinkeby', 'Rinkeby_Staging']
        include:
          - environment: 'Rinkeby'
            fleekfile: 'console.rinkeby.json'
            environment_name: 'rinkeby'
          - environment: 'Rinkeby_Staging'
            fleekfile: 'console.rinkeby.staging.json'
            environment_name: 'staging'
    runs-on: ubuntu-latest
    container: fleek/create-react-app:node-15
    environment: ${{ matrix.environment }}
    defaults:
      run:
        working-directory: ${{env.working-directory}}
    steps:
      - uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 14.15.5
      - name: Build the Govern
        run: cd ../govern && yarn install --frozen-lockfile && yarn build
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build the app
        run: CI='' yarn build
        env:
          REACT_APP_ANALYTICS_KEY: ${{ secrets.REACT_APP_ANALYTICS_KEY }}
          REACT_APP_DEPLOY_VERSION: ${{ github.sha }}
          REACT_APP_DEPLOY_ENVIRONMENT: ${{ matrix.environment_name }}
